### ISSUE TITLE
Wie soll mit inkonsistenten Angaben umgegangen werden? Auf welchen Daten soll der Fokus liegen?

### ISSUE THREAD

**Issue by TMink** [TMink/Digitales-3D-Feldbuch-Projekt-1-#2]

**Comment by JuHardtung** [comment]
Ich würde **alle Angaben** nutzen, die in den Vorgängerarbeiten erwähnt / genutzt wurden (selbst wenn diese nur einmalig aufgeführt wurden). Falls Begriffe synonym miteinander verwendet werden, sollte sich jeweils auf **einen Begriff geeinigt** werden. Diese Klärung kann (bzw. sollte) im Rahmen der Nutzerinterviews geschehen.
